name: Upload to Filecoin

# Runs AFTER build-pr.yml completes - HAS SECRETS
# Fork PRs will be detected and blocked with appropriate PR comments
on:
  workflow_run:
    workflows: ["Build PR Content"]  # Must match the name in build-pr.yml
    types:
      - completed
  workflow_dispatch:  # Allow manual testing

jobs:
  upload:
    # Only run if the build workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read  # Required to download artifacts from workflow_run
      checks: write  # Required to create PR check status
      pull-requests: write  # Required to comment on PRs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Download the build artifacts from the build workflow
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: site-dist
          path: dist
          github-token: ${{ github.token }}
          repository: ${{ github.event.workflow_run.repository.full_name }}
          run-id: ${{ github.event.workflow_run.id }}

      # Temporary allowlist of storage providers that have proven reliable during launch.
      # This exists to paper over early stability issues while the wider provider ecosystem
      # catches up. Remove once automatic provider discovery is trustworthy again.
      # Having a FilOz-approved set of SPs onchain is happening in https://github.com/FilOzone/filecoin-services/issues/291
      # This PROVIDER_ID set here will be used by the upload action below to override provider selection.
      - name: Select random known good provider
        run: |
          known_good_provider_ids=(2 8 16)
          selected_provider_id=${known_good_provider_ids[$RANDOM % ${#known_good_provider_ids[@]}]}
          echo "PROVIDER_ID=$selected_provider_id" >> $GITHUB_ENV
          echo "Selected known good provider ID: $selected_provider_id"

      # Upload to Filecoin using the downloaded build artifacts
      # The action will create a CAR file from the downloaded artifacts and upload to Filecoin
      - name: Upload to Filecoin
        uses: filecoin-project/filecoin-pin/upload-action@v0
        with:
          path: dist  # Path to the downloaded build artifacts
          walletPrivateKey: ${{ secrets.WALLET_PRIVATE_KEY }}
          network: calibration
          minStorageDays: "30"  # Hardcoded - The value committed in the main branch will be used, not the value in a modifying PR
          filecoinPayBalanceLimit: "0.25" # Hardcoded - The value committed in the main branch will be used, not the value in a modifying PR
